sudo: required
services: 
  - docker

before_install:
  - docker build -t hopisaurus/react-frontend-nginx -f Dockerfile.dev .

script:
  - docker run hopisaurus/react-frontend-nginx npm run test -- --coverage